### ISSUE TITLE
点按复制无法使用

### ISSUE THREAD

**Issue by bihdliulin** [CopyTranslator/CopyTranslator#128]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**点按复制无法使用**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v8.3.0 x86 版
 - 出现问题时的模式：专注模式
 - 操作系统：如win10 64位
 - 阅读器：Adobe Acrobat Pro DC
 - 出现问题的文档：附上文档文件
 - 出现问题的段落：第五段，第二句话

**如何复现这个问题**
重现行为的步骤：
1. 
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**都不可以使用**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
点按复制是实验功能，仅在部分PDF阅读器可用 admin Email:admin@hypercube.top Signature is customized by Netease Mail Master 在2019年05月28日 14:41，Lin Liu 写道： 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。 点按复制无法使用 （反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（ 复杂），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了） 系统环境（请填写以下信息）： CopyTranslator版本：如v8.3.0 x86 版 出现问题时的模式：专注模式 操作系统：如win10 64位 阅读器：Adobe Acrobat Pro DC 出现问题的文档：附上文档文件 出现问题的段落：第五段，第二句话 如何复现这个问题 重现行为的步骤： 1. 2. 3. 4. 问题出现时，当时的CopyTranslator的设置截图 请截取主模式窗口 都不可以使用 之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by FormatToday** [comment]
> 点按复制是实验功能，仅在部分PDF阅读器可用

请问哪些阅读器可以啊？

**Comment by elliottzheng** [comment]
> 
> 
> > 点按复制是实验功能，仅在部分PDF阅读器可用
> 
> 请问哪些阅读器可以啊？

我知道的有文电通PDF阅读器4
