### ISSUE TITLE
程序启动时鼠标会卡住大概10-15秒

### ISSUE THREAD

**Issue by aaron021512** [CopyTranslator/CopyTranslator#219]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
我使用的是OneQuick快捷键启动了CopyTranslator程序，打开了“关闭即退出”模式，就等于每次用每次打开，Alt+F4再关闭。
会偶发的出现，打开CopyTranslator后（程序是启动成功的，也读取到剪贴板了），鼠标忽然无法移动（硬件正常），键盘有时可以有时不行，类似于win的假死状态，10-15秒后就又恢复正常了。

这个问题很严重，我也没有把握能重现，之前没有任何其他应用程序出现过类似问题。
是否能提供一个类似这样的解决方案？

比如我把“关闭即退出”模式关闭，然后每次我按快捷键启动程序的时候，如果从未启动，就新启动一个CopyTranslator程序，如果发现已启动了（右下角），就可以显示程序窗口，等于CopyTranslator一直在运作，我只是用同一个快捷键去调出这个程序。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v9.0.1
 - 出现问题时的模式：MainMode/ FocusMode 都有
 - 操作系统：win10 64位
 - 阅读器：无
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
1. 无，如需其他log日志可提供
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
与阅读器无关

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
只用过这个版本

**Comment by elliottzheng** [comment]
我不太了解onequick，CopyTranslator不能保证全局单例，你是怎么调出来copytranslator的呢。

**Comment by aaron021512** [comment]
> 我不太了解onequick，CopyTranslator不能保证全局单例，你是怎么调出来copytranslator的呢。

我个人感觉和onequick无关，应该就是类似鼠标双击打开应用；如果不能保证全局单例，也应该是允许多例的存在吧？我的情况可能就是多例的时候发生的卡住

**Comment by elliottzheng** [comment]
双击打开应用会出现另一个实例，可能是因为启动实例而导致你卡顿的？

**Comment by aaron021512** [comment]
> 双击打开应用会出现另一个实例，可能是因为启动实例而导致你卡顿的？

是的，我基本可以100%重现，第一个实例完全启动完成，接着启动第二个就一定会卡住

**Comment by elliottzheng** [comment]
当copytranslator已经 之后，可以使用shift+f2 快速切换到对照模式，shift+f1 快速切换到专注模式，你可以尝试一下，也可以自行定义全局快捷键，参照https://copytranslator.github.io/guide/9.0.0.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A8%E5%B1%80%E5%BF%AB%E6%8D%B7%E9%94%AE

**Comment by aaron021512** [comment]
> 当copytranslator已经启动之后，可以使用shift+f2 快速切换到对照模式，shift+f1 快速切换到专注模式，你可以尝试一下，也可以自行定义全局快捷键，参照https://copytranslator.github.io/guide/9.0.0.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A8%E5%B1%80%E5%BF%AB%E6%8D%B7%E9%94%AE

emmm..这个我明白，但是我现在的问题是用快捷键有时候会打开2个实例，就会导致卡死10-15秒的问题，这个有办法解决吗？

**Comment by elliottzheng** [comment]
你怎么这么倔？copytranslator自己也能设置快捷键，你非得用别的软件再来开copytranslator?

--------------原始邮件--------------
发件人："aaron021512 "<notifications@github.com&gt;;
发送时间：2020年4月1日(星期三) 晚上6:15
收件人："CopyTranslator/CopyTranslator" <CopyTranslator@noreply.github.com&gt;;
抄送："Elliott Zheng "<admin@hypercube.top&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [CopyTranslator/CopyTranslator] 程序启动时鼠标会卡住大概10-15秒 (#219)
-----------------------------------

 

  
当copytranslator已经启动之后，可以使用shift+f2 快速切换到对照模式，shift+f1 快速切换到专注模式，你可以尝试一下，也可以自行定义全局快捷键，参照https://copytranslator.github.io/guide/9.0.0.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A8%E5%B1%80%E5%BF%AB%E6%8D%B7%E9%94%AE
  
emmm..这个我明白，但是我现在的问题是用快捷键有时候会打开2个实例，就会导致卡死10-15秒的问题，这个有办法解决吗？

**Comment by aaron021512** [comment]
> 你怎么这么倔？copytranslator自己也能设置快捷键，你非得用别的软件再来开copytranslator?
> […](#)
> --------------原始邮件-------------- 发件人："aaron021512 "<notifications@github.com&gt;; 发送时间：2020年4月1日(星期三) 晚上6:15 收件人："CopyTranslator/CopyTranslator" <CopyTranslator@noreply.github.com&gt;; 抄送："Elliott Zheng "<admin@hypercube.top&gt;;"Comment "<comment@noreply.github.com&gt;; 主题：Re: [CopyTranslator/CopyTranslator] 程序启动时鼠标会卡住大概10-15秒 (#219) ----------------------------------- 当copytranslator已经启动之后，可以使用shift+f2 快速切换到对照模式，shift+f1 快速切换到专注模式，你可以尝试一下，也可以自行定义全局快捷键，参照https://copytranslator.github.io/guide/9.0.0.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A8%E5%B1%80%E5%BF%AB%E6%8D%B7%E9%94%AE emmm..这个我明白，但是我现在的问题是用快捷键有时候会打开2个实例，就会导致卡死10-15秒的问题，这个有办法解决吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你是说copytranslator 可以使用全局快捷键启动？

**Comment by elliottzheng** [comment]
没有实例的时候不行，实例启动之后，可以用全局快捷键唤出，即使是在后台

--------------原始邮件--------------
发件人："aaron021512 "<notifications@github.com&gt;;
发送时间：2020年4月1日(星期三) 晚上6:30
收件人："CopyTranslator/CopyTranslator" <CopyTranslator@noreply.github.com&gt;;
抄送："Elliott Zheng "<admin@hypercube.top&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [CopyTranslator/CopyTranslator] 程序启动时鼠标会卡住大概10-15秒 (#219)
-----------------------------------

 

  
你怎么这么倔？copytranslator自己也能设置快捷键，你非得用别的软件再来开copytranslator?
 …
 --------------原始邮件-------------- 发件人："aaron021512 "<notifications@github.com&gt;; 发送时间：2020年4月1日(星期三) 晚上6:15 收件人："CopyTranslator/CopyTranslator" <CopyTranslator@noreply.github.com&gt;; 抄送："Elliott Zheng "<admin@hypercube.top&gt;;"Comment "<comment@noreply.github.com&gt;; 主题：Re: [CopyTranslator/CopyTranslator] 程序启动时鼠标会卡住大概10-15秒 (#219) ----------------------------------- 当copytranslator已经启动之后，可以使用shift+f2 快速切换到对照模式，shift+f1 快速切换到专注模式，你可以尝试一下，也可以自行定义全局快捷键，参照https://copytranslator.github.io/guide/9.0.0.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A8%E5%B1%80%E5%BF%AB%E6%8D%B7%E9%94%AE emmm..这个我明白，但是我现在的问题是用快捷键有时候会打开2个实例，就会导致卡死10-15秒的问题，这个有办法解决吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你是说copytranslator 可以使用全局快捷键启动？

**Comment by elliottzheng** [comment]
此问题已在v10解决，由于v10限制单例，当全局存在实例时，启动的第二个实例将自动退出，同时焦点会转移至原有实例窗口。

https://www.electronjs.org/docs/api/app#apprequestsingleinstancelock
