### ISSUE TITLE
[Features]求增加字号调节功能~感谢~

### ISSUE THREAD

**Issue by ZhengZou-0210** [CopyTranslator/CopyTranslator#272]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.github.io/guide/)和项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
没有问题。

**描述您想要的解决方案**
增加字号调节功能

**描述您考虑过的替代方案**
暂无
**附加背景**
没有

**Comment by elliottzheng** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    ctrl+滚轮或者是ctrl+和ctrl-调节字体大小
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                admin
                            
                    
                        
                            
                                    admin@hypercube.top
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年7月20日 00:06，ZhengZou-0210<notifications@github.com> 写道： 




重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读使用指南和项目的project并在Issuse中查找您问题的关键词，您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了，CopyTranslator经过多次迭代，功能越来越丰富（复杂），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。
您的功能请求是否与问题有关？请描述一下.
没有问题。
描述您想要的解决方案
增加字号调节功能
描述您考虑过的替代方案
暂无
附加背景
没有

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.
