### ISSUE TITLE
复制后copyTranslator需要很长时间显示剪切板的内容

### ISSUE THREAD

**Issue by chzhyang** [CopyTranslator/CopyTranslator#419]
## 描述问题
复制后copyTranslator需要很长时间显示剪切板的内容
### 系统环境（请填写以下信息）

- CopyTranslator v9.0.3 v9.1.0
- 出现问题时的模式：对照模式
- 操作系统：win10 64位 专业版 英文系统
- 安装路径: 默认的c盘安装路径
- 额外配置： 三屏，1-2-3，1为笔记本显示器，缩放150%，2为1080p显示器，缩放100%，3为4K屏（设为主屏），缩放150%。关闭多屏，在笔记本屏幕上问题依旧。

### 如何复现这个问题

详细描述问题的现象：
- 监听剪切板速度特别慢，复制后很久才会显示在软件界面
- 阅读器和copyTranslator同在4k屏、1080p或者笔记本屏幕，或者分别在不同的屏幕，都存在同样的问题

详细描述重现问题的步骤：

- 常规复制操作

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**

- 下载后直接使用就有这个问题，配置文件未改动。

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。

- 问题依然存在。

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**

- 已测试浏览器、md阅读器、vscode、pdf阅读器，问题同样存在

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？

- 切换baidu、youdao等翻译引擎，问题依然存在。

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。

- 无关

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号

- 之前在中文版win10上使用没有问题，双屏2k屏也没有问题

**Comment by qstdnx** [comment]
同样的问题……

**Comment by Suyixiu** [comment]
+1

**Comment by Theigrams** [comment]
应该不是监听剪切板慢，我直接把句子复制进去，也得等很久才出来，感觉是网络的问题，一开始猜测是用的人多了，服务器不够用了，但是我把百度的API换成自己的，还是很慢才，Google也是。

这种情况以前偶尔发生，最近经常出现，换了 v9 和 v10 的版本，在 win10 和 MacOS12 上也一样是这样的问题

**Comment by tfwang96** [comment]
我也是一样，有什么解决思路吗？弄了弄完全搞不定。

**Comment by 1363279100** [comment]
没法解决，bug太多，我已经换Xtranslator了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CopyTranslator/CopyTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 上午9:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [CopyTranslator/CopyTranslator] 复制后copyTranslator需要很长时间显示剪切板的内容 (Issue #419)





 
我也是一样，有什么解决思路吗？弄了弄完全搞不定。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Theigrams** [comment]
后续找了一些代替品，Xtranslator不错但要发朋友圈宣传。
Mac 上有开源的 https://github.com/ripperhe/Bob，但如果google翻译的话得自己提供API

**Comment by deyangfan** [comment]
设置-布局-由“compare”模式切换到“vertical”模式就很快，大概率是网络问题。我选compare模式复制后要等一会儿也可以翻译出来。

**Comment by deyangfan** [comment]
“设置”-“翻译设置”-“translator-auto”选项中，把google去掉；“translator-double”选项中选youdao，可以解决复制后翻译很慢的问题。版本是v10.0

**Comment by deyangfan** [comment]
“设置”-“布局”选项中，把“compare”切换成“vertical”可以解决复制后翻译慢的问题，版本v10.0。猜测大概率是网络问题，不切换时挂梯子复制后要等一会儿也可翻译出来，就是搞心态了。

**Comment by 1363279100** [comment]
可以通过改手机时间让发的朋友圈变成两小时前😄



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月19日(周五) 晚上8:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CopyTranslator/CopyTranslator] 复制后copyTranslator需要很长时间显示剪切板的内容 (Issue #419)




 
后续找了一些代替品，Xtranslator不错但要发朋友圈宣传。
 Mac 上有开源的 https://github.com/ripperhe/Bob，但如果google翻译的话得自己提供API
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CarlossShi** [comment]
+1, 一直谷歌翻句子, 有道翻词语, 黄灯时间很长, 10.0问题比较严重, 后来换成9.1.1仍有这个问题.

**Comment by JDYG** [comment]
+1,不确定是什么问题，我这边挂了代理，google也能开，就是剪贴板上复制的，一直无法翻译。

**Comment by xujinming01** [comment]
+1，翻译要很久才显示。

**Comment by wzy011030** [comment]
这是一封来自QQ邮箱的自动回复邮件。 您好，您的邮件我已收到，谢谢您的来信。

**Comment by GYJ09** [comment]
已经不太好用了，应该是软件的Bug,周围的人都出现了这个问题，很久都不显示翻译的结果。

**Comment by GYJ09** [comment]
> 10.0同样的问题……

你不孤独

**Comment by GYJ09** [comment]
> 应该不是监听剪切板慢，我直接把句子复制进去，也得等很久才出来，感觉是网络的问题，一开始猜测是用的人多了，服务器不够用了，但是我把百度的API换成自己的，还是很慢才，Google也是。
> 
> 这种情况以前偶尔发生，最近经常出现，换了 v9 和 v10 的版本，在 win10 和 MacOS12 上也一样是这样的问题

和你一样 很久不出结果 所有引擎都是这样 换网络也不行

**Comment by Magician-MO** [comment]
v10 beta5 同

**Comment by wzy011030** [comment]
这是一封来自QQ邮箱的自动回复邮件。 您好，您的邮件我已收到，谢谢您的来信。

**Comment by elliottzheng** [comment]
请尝试[最新版本](https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.0.0) 并反馈问题，谢谢
